insert into pizzas (pizza_code, name,description, price_small, price_big) values ('MARG', 'Margherita', 'tomato sauce, fresh mozzarela, virgin olive oil, garlic', 400, 1000);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('VEGE', 'Vegetariana', 'tomato sauce, fresh mozzarela, virgin olive oil, vegies', 450, 1200);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('PEPP', 'Pepperoni', 'tomato sauce, fresh mozzarela, pepperoni', 500, 1300);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('FICA', 'Ficante', 'tomato sauce, fresh mozzarela, red hot chili pepper, jalapeno', 550,1450);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('NAPO', 'Napoletana', 'tomato sauce, fresh mozzarela, anchovies, oregano', 650, 1550);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('SICI', 'Siciliana', 'tomato sauce, anchovies, capers, olives, oregano', 750, 1800);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('FUNG', 'Funghi', 'tomato sauce, fresh mozzarela, virgin olive oil, garlic', 800, 1600);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('PARM', 'Parma', 'tomato sauce, fresh mozzarela, virgin olive oil, raw ham', 300, 1250);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('SALS', 'Salscoo', 'tomato sauce, fresh mozzarela, virgin olive oil, garlic, frankfurter', 800, 1800);
insert into pizzas (pizza_code, name,description, price_small, price_big) values ('HAVA', 'Havaian', 'tomato sauce, fresh mozzarela, virgin olive oil, pineapple', 550, 1450);